server{
	listen 80;
	listen 443 ssl;
	server_name myapp.local;
	ssl_certificate /etc/nginx/ssl/myapp/myapp.local.crt;
	ssl_certificate_key /etc/nginx/ssl/myapp/myapp.local.key;

	access_log /var/log/nginx/myapp_access.log;
	error_log /var/log/nginx/myapp_error.log;

	root /var/www/myapp;
	index index.html;

	location / {
		try_files $uri $uri/ =404 ;
	}		

	location /status {
		stub_status on;
		allow 127.0.0.1;
		deny all;
	}
	location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php8.5-fpm.sock;
	}
}
