server{
	listen 80;
	server_name myapp.local;

	access_log /var/nginx/myapp_access.log;
	error_log /var/nginx/myapp_error.log;

	root var/www/myapp;
	index index.html;

	location / {
		try_files $uri $uri/=404 ;
	}

	location /status {
		stub_status on;
		allow 127.0.0.1;
		deny all;
	}
}
